name: webapp_pesquisa_avalicao_dashboard
description: "Pesquisa de Avaliação Dashboard"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0 
  intl: ^0.20.2
  shared_preferences: ^2.0.0 
  firebase_core: ^3.10.0 
  cloud_firestore: 
  firebase_auth:        
  firebase_storage:     
  firebase_messaging:    
  firebase_analytics:   
  firebase_crashlytics: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: 


# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
   